name: ci

on:
  push:
    branches: [ "sprint-2", "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root

      - name: Lint + Format (ruff / black / isort)
        run: |
          ruff check . --fix
          black .
          isort .

      - name: Verify formatting
        run: |
          black --check .
          isort --check-only .


      - name: Run tests (pytest)
        env:
          TEST_DATABASE_URL: sqlite:///./test.db
        run: |
          pytest -q